version: '3.9'
services:
  db:
    container_name: bewise_database
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - bewise_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 5s
      timeout: 10s
      retries: 3

  pgadmin:
    container_name: bewise_pgadmin
    image: dpage/pgadmin4:7
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - bewise_network
    restart: unless-stopped

  api:
    container_name: bewise_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    networks:
      - bewise_network
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin:

networks:
  bewise_network:
    name: "bewise_network"